services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: extractive_qa_api
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app/src
      MLRUNS_DIR: /app/artifacts/mlruns
    command: python -m uvicorn extractive_qa_mlops.api:app --host 0.0.0.0 --port 8000

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: extractive_qa_ui
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    command: streamlit run /app/ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - api
